name: nightly-cbb-preds

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # (Optional) show files so you can confirm the path
      - name: List repo files
        run: |
          pwd
          ls -la
          echo "--- data dir ---"
          ls -la data || true

      - name: Generate predictions.csv
        env:
          INPUT_CSV: data/november_games.csv    # <-- set the correct path here
          OUTPUT_CSV: predictions.csv
        run: python make_predictions.py

      - name: Commit predictions.csv
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update predictions.csv"
          file_pattern: predictions.csv
