name: nightly-cbb-preds

on:
  schedule:
    - cron: '0 12 * * *'   # daily 12:00 UTC (8am ET)
  workflow_dispatch:        # allow manual runs

permissions:
  contents: write           # needed to commit predictions.csv

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # If you later need requirements.txt, add a pip install step here

      - name: Generate predictions.csv
        run: |
          python make_predictions.py

      - name: Commit predictions.csv
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update predictions.csv"
          file_pattern: predictions.csv
